# -*- coding: utf-8 -*-
"""Coefficient de Silhouette.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XNk2QoU4rcOClCzEVcJpLxLox4Y0Ql8Z
"""

from sklearn.datasets import make_blobs
X,y = make_blobs(n_samples=600, centers=4, n_features=2)

import matplotlib.pyplot as plt
plt.scatter(X[:,0],X[:,1])
plt.show()

from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans

k = range(2,11)
for i in k:
  km = KMeans(n_clusters=i)
  km= km.fit(X)
  silhouette_avg = silhouette_score(X, km.labels_)
  print("For n_clusters =", i,
        "The average silhouette_score is :", silhouette_avg)

from yellowbrick.cluster import SilhouetteVisualizer

for n_clusters in k:
  plt.subplot(1,2,1)
  model = KMeans(n_clusters)
  Visualizer = SilhouetteVisualizer(model, colors='yellowbrick')
  Visualizer.fit(X)
  plt.subplot(1,2,2)
  plt.scatter(X[:, 0], X[:, 1], c=model.labels_, cmap="plasma")
  Visualizer.show()